# config.yml
blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/paolobellini/laravel-er/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/paolobellini/laravel-er/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/paolobellini/laravel-er/security/advisories/new
    about: Report vulnerabilities privately
