name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3, 8.4, 8.5 ]
        laravel: [ '12.*' ]
        include:
          - laravel: 12.*
            testbench: ^10.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, xdebug
          coverage: xdebug

      - name: Install Dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run type coverage
        run: composer test:type-coverage

      - name: Run tests
        run: composer test:unit